name: Danger
run-name: ${{ github.actor }} is using Danger Gem ⚠️
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: gem install danger
      - run: bundle exec danger --dangerfile=Dangerfile --danger_id=danger-pr
env:
  # the token used by danger to report the results on the PR
  DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}